id: P000604
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1017352
  title: རྡོ་རྗེའི་མགུར་དྲུག་གསུང་རྒྱུན་ཐོར་བུ
  author: ''
  volumes:
    d7a3266eca604e4dbb17e8d1e06cd7fc:
      image_group_id: I00EGS1017354
      title: ''
      volume_number: 1
      total_pages: 258
