id: P000604
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W00EGS1017352
  title: རྡོ་རྗེའི་མགུར་དྲུག་གསུང་རྒྱུན་ཐོར་བུ
  author: ''
  volumes:
    d7a3266eca604e4dbb17e8d1e06cd7fc:
      image_group_id: I00EGS1017354
      title: ''
      volume_number: 1
      total_pages: 258
