id: I161CEC48
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T22:24:10+00:00'
last_modified: '2022-06-07T12:25:57.448908+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00EGS1017352
  title: རྡོ་རྗེའི་མགུར་དྲུག་གསུང་རྒྱུན་ཐོར་བུ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    5F3B:
      image_group_id: I00EGS1017354
      title: ''
      total_pages: 258
      order: 1
      base_file: 5F3B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
