id: I161CEC48
legacy_id: P000604
ocr_import_info:
  bdrc_scan_id: W00EGS1017352
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T22:22:21'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-29T11:08:22.273232+00:00'
last_modified: 2022-08-29 19:08:50.506881
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00EGS1017352
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW00EGS1017352
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྡོ་རྗེའི་མགུར་དྲུག་གསུང་རྒྱུན་ཐོར་བུ།
  author: རྗེ་བཙུན་མི་ལ་རས་པ།
statistics:
  ocr_word_mean_confidence_index: 0.6783488871568545
  ocr_word_median_confidence_index: 0.7300000190734863
quality: null
bases:
  I00EGS1017354:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1017354
      total_pages: 258
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00EGS1017354.txt
    statistics:
      ocr_word_median_confidence_index: 0.7300000190734863
      ocr_word_mean_confidence_index: 0.6783488871568545
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
